<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.233" tests="8" errors="7" skipped="0" failures="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.91-b14"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="BR"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/aluno/spring-projects/maven/spring-data-redis"/>
    <property name="java.runtime.version" value="1.8.0_91-b14"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="3.13.0-91-generic"/>
    <property name="user.home" value="/home/aluno"/>
    <property name="user.timezone" value="America/Fortaleza"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="aluno"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-oracle/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="pt"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_91"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="testGetResourceValidate" classname="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.099">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException">org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResourceValidate(JredisPoolTests.java:86)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResourceValidate(JredisPoolTests.java:86)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResourceValidate(JredisPoolTests.java:86)
</error>
    <system-err><![CDATA[01475611401561 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611401577 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1702146597
01475611401578 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testReturnBrokenResource" classname="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.004">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException">org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testReturnBrokenResource(JredisPoolTests.java:118)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testReturnBrokenResource(JredisPoolTests.java:118)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testReturnBrokenResource(JredisPoolTests.java:118)
</error>
    <system-err><![CDATA[01475611401585 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611401586 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1576861390
01475611401586 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testGetResourceCreationUnsuccessful" classname="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.002"/>
  <testcase name="testGetResourcePoolExhausted" classname="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.008">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException">org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResourcePoolExhausted(JredisPoolTests.java:71)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResourcePoolExhausted(JredisPoolTests.java:71)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResourcePoolExhausted(JredisPoolTests.java:71)
</error>
    <system-err><![CDATA[01475611401596 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611401597 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1681595665
01475611401597 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testGetResource" classname="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.003">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException">org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResource(JredisPoolTests.java:60)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResource(JredisPoolTests.java:60)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testGetResource(JredisPoolTests.java:60)
</error>
    <system-err><![CDATA[01475611401599 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611401600 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1828757853
01475611401600 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testCreateWithHostAndPort" classname="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.004">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException">org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testCreateWithHostAndPort(JredisPoolTests.java:132)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testCreateWithHostAndPort(JredisPoolTests.java:132)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testCreateWithHostAndPort(JredisPoolTests.java:132)
</error>
    <system-err><![CDATA[01475611401603 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611401604 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@2140832232
01475611401604 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testReturnResource" classname="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.003">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException">org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testReturnResource(JredisPoolTests.java:105)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testReturnResource(JredisPoolTests.java:105)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testReturnResource(JredisPoolTests.java:105)
</error>
    <system-err><![CDATA[01475611401606 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611401606 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:0 | SyncConnection@1935365522
01475611401607 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testCreateWithHostPortAndDbIndex" classname="org.springframework.data.redis.connection.jredis.JredisPoolTests" time="0.004">
    <error message="Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.springframework.data.redis.connection.PoolException">org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testCreateWithHostPortAndDbIndex(JredisPoolTests.java:138)
Caused by: org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testCreateWithHostPortAndDbIndex(JredisPoolTests.java:138)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.connection.jredis.JredisPoolTests.testCreateWithHostPortAndDbIndex(JredisPoolTests.java:138)
</error>
    <system-err><![CDATA[01475611401608 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611401609 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:1 | SyncConnection@1410986873
01475611401609 Tue Oct 04 17:03:21 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
</testsuite>