<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="481.529" tests="12" errors="12" skipped="0" failures="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.91-b14"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="BR"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/aluno/spring-projects/maven/spring-data-redis"/>
    <property name="java.runtime.version" value="1.8.0_91-b14"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="3.13.0-91-generic"/>
    <property name="user.home" value="/home/aluno"/>
    <property name="user.timezone" value="America/Fortaleza"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="aluno"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-oracle/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="pt"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_91"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="testStopMessageListenerContainers[0]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.82">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
</error>
    <system-out><![CDATA[2016-10-04 16:55:15,355 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:20,360 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:20,444 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:25,451 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:25,544 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:30,551 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:30,645 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:35,646 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:35,746 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:40,747 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:40,847 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:45,854 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:45,947 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:50,949 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:51,048 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:55:56,049 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testStopListening[0]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.009">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
</error>
    <system-out><![CDATA[2016-10-04 16:55:56,154 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:01,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:01,170 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:06,156 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:06,172 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:06,172 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:11,157 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:11,160 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:11,173 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:11,173 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:16,158 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:16,158 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:16,161 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:16,175 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:16,175 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:21,159 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:21,159 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:21,163 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:21,164 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:21,179 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:21,179 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:26,160 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:26,161 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:26,162 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:26,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:26,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:26,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:26,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:31,160 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:31,182 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:31,183 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:31,185 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:31,204 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:31,204 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:31,204 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:31,204 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testRemoveLastListener[0]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.006">
    <error message="Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
</error>
    <system-out><![CDATA[2016-10-04 16:56:36,163 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:41,163 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:41,164 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:46,164 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:46,164 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:46,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:51,164 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:51,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:51,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:51,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:56,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:56,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:56,166 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:56,167 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:56:56,168 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:01,165 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:01,166 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:01,166 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:01,167 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:01,175 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:01,175 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:06,166 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:06,167 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:06,167 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:06,167 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:06,168 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:06,176 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:06,176 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:11,167 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:11,167 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:11,168 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:11,168 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:11,169 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:11,171 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:11,177 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:11,177 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testStopMessageListenerContainers[1]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.007">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
</error>
    <system-out><![CDATA[2016-10-04 16:57:16,333 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:21,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:26,181 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:31,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:36,177 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:41,243 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:46,196 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:57:52,242 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testStopListening[1]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.051">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
</error>
    <system-out><![CDATA[2016-10-04 16:57:56,178 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:01,178 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:01,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:06,178 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:06,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:06,181 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:11,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:11,181 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:11,182 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:11,183 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:16,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:16,181 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:16,184 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:16,186 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:16,189 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:21,180 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:21,182 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:21,183 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:21,186 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:21,187 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:21,191 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:26,234 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:26,236 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:26,240 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:26,241 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:26,242 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:26,243 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:26,244 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:31,226 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:31,235 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:31,241 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:31,242 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:31,243 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:31,243 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:31,244 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:31,245 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testRemoveLastListener[1]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.016">
    <error message="Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis on 127.0.0.1:6379; nested exception is com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
Caused by: com.lambdaworks.redis.RedisConnectionException: Unable to connect to /127.0.0.1:6379
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
Caused by: java.net.ConnectException: Conexão recusada: /127.0.0.1:6379
</error>
    <system-out><![CDATA[2016-10-04 16:58:36,228 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:41,229 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:41,230 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:46,229 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:46,230 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:46,231 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:51,230 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:51,231 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:51,232 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:51,235 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:56,231 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:56,232 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:56,233 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:56,234 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:58:56,236 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:01,231 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:01,232 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:01,234 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:01,235 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:01,236 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:01,238 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:06,232 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:06,232 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:06,234 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:06,234 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:06,236 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:06,237 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:06,238 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:11,231 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:11,233 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:11,233 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:11,235 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:11,235 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:11,237 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:11,238 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:11,239 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testStopMessageListenerContainers[2]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="39.997">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
</error>
    <system-out><![CDATA[2016-10-04 16:59:16,433 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:21,234 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:26,235 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:31,235 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:36,236 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:41,236 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:46,239 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 16:59:51,239 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testStopListening[2]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.005">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
</error>
    <system-out><![CDATA[2016-10-04 16:59:56,243 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:01,243 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:01,244 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:06,243 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:06,244 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:06,248 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:11,244 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:11,244 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:11,245 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:11,249 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:16,244 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:16,246 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:16,246 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:16,246 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:16,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:21,245 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:21,245 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:21,247 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:21,247 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:21,247 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:21,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:26,245 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:26,246 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:26,246 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:26,248 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:26,248 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:26,248 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:26,251 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:31,246 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:31,257 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:31,257 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:31,258 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:31,258 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:31,258 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:31,258 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:31,259 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testRemoveLastListener[2]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.005">
    <error message="Could not connect; nested exception is redis.client.RedisException: Could not connect" type="org.springframework.data.redis.RedisConnectionFailureException">org.springframework.data.redis.RedisConnectionFailureException: Could not connect; nested exception is redis.client.RedisException: Could not connect
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
Caused by: redis.client.RedisException: Could not connect
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
Caused by: java.net.ConnectException: Conexão recusada
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
</error>
    <system-out><![CDATA[2016-10-04 17:00:36,248 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:41,248 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:41,249 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:46,249 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:46,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:46,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:51,249 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:51,252 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:51,253 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:51,253 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:56,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:56,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:56,253 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:56,255 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:00:56,255 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:01,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:01,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:01,251 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:01,255 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:01,255 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:01,257 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:06,250 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:06,251 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:06,252 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:06,252 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:06,257 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:06,257 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:06,258 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:11,251 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:11,252 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:11,253 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:11,253 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:11,253 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:11,258 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:11,258 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
2016-10-04 17:01:11,258 ERROR s.listener.RedisMessageListenerContainer: 647 - Connection failure occurred. Restarting subscription task after 5000 ms
]]></system-out>
  </testcase>
  <testcase name="testStopMessageListenerContainers[3]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.009">
    <error message="null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.jredis.ClientRuntimeException">org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopMessageListenerContainers(SubscriptionConnectionTests.java:152)
</error>
    <system-out><![CDATA[2016-10-04 17:01:16,320 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:01:21,256 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:01:26,256 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:01:31,256 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:01:36,256 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:01:41,257 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:01:46,258 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:01:51,259 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
]]></system-out>
    <system-err><![CDATA[01475611276312 Tue Oct 04 17:01:16 BRT 2016 JRedis[tid:285] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611276317 Tue Oct 04 17:01:16 BRT 2016 JRedis[tid:285] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@641208490
01475611276318 Tue Oct 04 17:01:16 BRT 2016 JRedis[tid:285] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611281253 Tue Oct 04 17:01:21 BRT 2016 JRedis[tid:286] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611281255 Tue Oct 04 17:01:21 BRT 2016 JRedis[tid:286] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@379339408
01475611281255 Tue Oct 04 17:01:21 BRT 2016 JRedis[tid:286] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611286254 Tue Oct 04 17:01:26 BRT 2016 JRedis[tid:287] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611286255 Tue Oct 04 17:01:26 BRT 2016 JRedis[tid:287] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1224569477
01475611286256 Tue Oct 04 17:01:26 BRT 2016 JRedis[tid:287] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611291254 Tue Oct 04 17:01:31 BRT 2016 JRedis[tid:288] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611291256 Tue Oct 04 17:01:31 BRT 2016 JRedis[tid:288] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@2044995802
01475611291256 Tue Oct 04 17:01:31 BRT 2016 JRedis[tid:288] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611296255 Tue Oct 04 17:01:36 BRT 2016 JRedis[tid:289] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611296256 Tue Oct 04 17:01:36 BRT 2016 JRedis[tid:289] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1241711478
01475611296256 Tue Oct 04 17:01:36 BRT 2016 JRedis[tid:289] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611301256 Tue Oct 04 17:01:41 BRT 2016 JRedis[tid:290] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611301257 Tue Oct 04 17:01:41 BRT 2016 JRedis[tid:290] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@137182524
01475611301257 Tue Oct 04 17:01:41 BRT 2016 JRedis[tid:290] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611306256 Tue Oct 04 17:01:46 BRT 2016 JRedis[tid:291] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611306257 Tue Oct 04 17:01:46 BRT 2016 JRedis[tid:291] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@840265127
01475611306257 Tue Oct 04 17:01:46 BRT 2016 JRedis[tid:291] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611311257 Tue Oct 04 17:01:51 BRT 2016 JRedis[tid:292] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611311258 Tue Oct 04 17:01:51 BRT 2016 JRedis[tid:292] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1336269144
01475611311258 Tue Oct 04 17:01:51 BRT 2016 JRedis[tid:292] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611316256 Tue Oct 04 17:01:56 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611316258 Tue Oct 04 17:01:56 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1496355635
01475611316258 Tue Oct 04 17:01:56 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testStopListening[3]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="40.006">
    <error message="null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.jredis.ClientRuntimeException">org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testStopListening(SubscriptionConnectionTests.java:201)
</error>
    <system-out><![CDATA[2016-10-04 17:01:56,263 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:01,263 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:06,264 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:11,264 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:16,264 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:21,265 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:26,265 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:31,266 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
]]></system-out>
    <system-err><![CDATA[01475611316261 Tue Oct 04 17:01:56 BRT 2016 JRedis[tid:293] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611316262 Tue Oct 04 17:01:56 BRT 2016 JRedis[tid:293] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1961112422
01475611316262 Tue Oct 04 17:01:56 BRT 2016 JRedis[tid:293] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611321261 Tue Oct 04 17:02:01 BRT 2016 JRedis[tid:294] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611321262 Tue Oct 04 17:02:01 BRT 2016 JRedis[tid:294] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1865403622
01475611321262 Tue Oct 04 17:02:01 BRT 2016 JRedis[tid:294] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611326261 Tue Oct 04 17:02:06 BRT 2016 JRedis[tid:295] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611326262 Tue Oct 04 17:02:06 BRT 2016 JRedis[tid:295] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@140432885
01475611326263 Tue Oct 04 17:02:06 BRT 2016 JRedis[tid:295] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611331262 Tue Oct 04 17:02:11 BRT 2016 JRedis[tid:296] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611331263 Tue Oct 04 17:02:11 BRT 2016 JRedis[tid:296] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@2080608964
01475611331263 Tue Oct 04 17:02:11 BRT 2016 JRedis[tid:296] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611336262 Tue Oct 04 17:02:16 BRT 2016 JRedis[tid:297] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611336263 Tue Oct 04 17:02:16 BRT 2016 JRedis[tid:297] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@10960850
01475611336263 Tue Oct 04 17:02:16 BRT 2016 JRedis[tid:297] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611341263 Tue Oct 04 17:02:21 BRT 2016 JRedis[tid:298] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611341264 Tue Oct 04 17:02:21 BRT 2016 JRedis[tid:298] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1736195275
01475611341264 Tue Oct 04 17:02:21 BRT 2016 JRedis[tid:298] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611346263 Tue Oct 04 17:02:26 BRT 2016 JRedis[tid:299] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611346264 Tue Oct 04 17:02:26 BRT 2016 JRedis[tid:299] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@39078539
01475611346264 Tue Oct 04 17:02:26 BRT 2016 JRedis[tid:299] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611351264 Tue Oct 04 17:02:31 BRT 2016 JRedis[tid:300] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611351265 Tue Oct 04 17:02:31 BRT 2016 JRedis[tid:300] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1120809184
01475611351265 Tue Oct 04 17:02:31 BRT 2016 JRedis[tid:300] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611356264 Tue Oct 04 17:02:36 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611356265 Tue Oct 04 17:02:36 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@2127036371
01475611356265 Tue Oct 04 17:02:36 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
  <testcase name="testRemoveLastListener[3]" classname="org.springframework.data.redis.listener.SubscriptionConnectionTests" time="39.965">
    <error message="null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: =&gt; [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]" type="org.jredis.ClientRuntimeException">org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.springframework.data.redis.listener.SubscriptionConnectionTests.testRemoveLastListener(SubscriptionConnectionTests.java:177)
</error>
    <system-out><![CDATA[2016-10-04 17:02:36,269 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:41,269 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:46,270 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:51,270 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:02:56,270 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:03:01,271 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:03:06,271 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
2016-10-04 17:03:11,272 ERROR s.listener.RedisMessageListenerContainer: 652 - SubscriptionTask aborted with exception:
org.jredis.ClientRuntimeException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero] cause: => [IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]]
	at org.jredis.ri.alphazero.JRedisClient.setConnection(JRedisClient.java:158)
	at org.jredis.ri.alphazero.JRedisClient.<init>(JRedisClient.java:93)
	at org.springframework.data.redis.connection.jredis.JredisConnectionFactory.getConnection(JredisConnectionFactory.java:106)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:732)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: null reference:{connection on setConnection()} in method JRedisClient.setConnection() [file: JRedisClient.java line:158 - package: org.jredis.ri.alphazero]
	at org.jredis.ri.alphazero.support.Assert.throwIt(Assert.java:270)
	at org.jredis.ri.alphazero.support.Assert.notNull(Assert.java:104)
	... 5 common frames omitted
]]></system-out>
    <system-err><![CDATA[01475611356267 Tue Oct 04 17:02:36 BRT 2016 JRedis[tid:301] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611356268 Tue Oct 04 17:02:36 BRT 2016 JRedis[tid:301] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1848638132
01475611356269 Tue Oct 04 17:02:36 BRT 2016 JRedis[tid:301] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611361267 Tue Oct 04 17:02:41 BRT 2016 JRedis[tid:302] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611361268 Tue Oct 04 17:02:41 BRT 2016 JRedis[tid:302] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1385080807
01475611361268 Tue Oct 04 17:02:41 BRT 2016 JRedis[tid:302] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611366268 Tue Oct 04 17:02:46 BRT 2016 JRedis[tid:303] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611366269 Tue Oct 04 17:02:46 BRT 2016 JRedis[tid:303] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@2694074
01475611366269 Tue Oct 04 17:02:46 BRT 2016 JRedis[tid:303] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611371268 Tue Oct 04 17:02:51 BRT 2016 JRedis[tid:304] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611371269 Tue Oct 04 17:02:51 BRT 2016 JRedis[tid:304] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1908197529
01475611371270 Tue Oct 04 17:02:51 BRT 2016 JRedis[tid:304] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611376269 Tue Oct 04 17:02:56 BRT 2016 JRedis[tid:305] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611376269 Tue Oct 04 17:02:56 BRT 2016 JRedis[tid:305] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1158746273
01475611376270 Tue Oct 04 17:02:56 BRT 2016 JRedis[tid:305] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611381269 Tue Oct 04 17:03:01 BRT 2016 JRedis[tid:306] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611381270 Tue Oct 04 17:03:01 BRT 2016 JRedis[tid:306] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1280778366
01475611381271 Tue Oct 04 17:03:01 BRT 2016 JRedis[tid:306] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611386270 Tue Oct 04 17:03:06 BRT 2016 JRedis[tid:307] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611386271 Tue Oct 04 17:03:06 BRT 2016 JRedis[tid:307] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1241182616
01475611386271 Tue Oct 04 17:03:06 BRT 2016 JRedis[tid:307] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611391270 Tue Oct 04 17:03:11 BRT 2016 JRedis[tid:308] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611391272 Tue Oct 04 17:03:11 BRT 2016 JRedis[tid:308] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@1179411803
01475611391272 Tue Oct 04 17:03:11 BRT 2016 JRedis[tid:308] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
01475611396270 Tue Oct 04 17:03:16 BRT 2016 JRedis[tid:1] <INFORMAÇÕES>: WARNING: heartbeat is disabled.
01475611396271 Tue Oct 04 17:03:16 BRT 2016 JRedis[tid:1] <ADVERTÊNCIA>: PROBLEM: Shutting down due to connection FAULT: Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379 - Connection: SYNCHRONOUS  localhost/127.0.0.1:6379 db:2 | SyncConnection@106374177
01475611396271 Tue Oct 04 17:03:16 BRT 2016 JRedis[tid:1] <GRAVE>: Error creating connection -> Socket connect failed [cause: java.net.ConnectException: Conexão recusada] -- make sure the server is running at localhost:6379
]]></system-err>
  </testcase>
</testsuite>